version: '3'
services:
  transferbase-database:
    image: 'postgres:12.1-alpine'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/transferbase
    ports:
      - "3000:3000"
    depends_on:
      - transferbase-database
    